Repository team-bofit/bofit-server, pull requests merged in 2025-07, with the labels that each got.

#11 [Feat] 도커 파일 추가
  .gitignore
  Dockerfile
  build.gradle
  src/main/resources/application.yml
  src/test/java/org/sopt/bofit/BofitApplicationTests.java
Labels: 🌏 Deploy, ⚙ Setting, 🔥재헌

#13 [Feat] 카카오 로그인 및 JWT 관련 구현
  build.gradle
  src/main/java/org/sopt/bofit/domain/user/entity/User.java
  src/main/java/org/sopt/bofit/domain/user/repository/UserRepository.java
  src/main/java/org/sopt/bofit/global/annotation/LoginUserId.java
  src/main/java/org/sopt/bofit/global/config/SecurityConfig.java
  src/main/java/org/sopt/bofit/global/config/WebConfig.java
  src/main/java/org/sopt/bofit/global/config/swagger/SwaggerConfig.java
  src/main/java/org/sopt/bofit/global/config/swagger/SwaggerResponseDescription.java
  src/main/java/org/sopt/bofit/global/exception/GlobalExceptionHandler.java
  src/main/java/org/sopt/bofit/global/exception/constant/GlobalErrorCode.java
  src/main/java/org/sopt/bofit/global/exception/constant/OAuthErrorCode.java
  src/main/java/org/sopt/bofit/global/exception/custom_exception/BadRequestException.java
  src/main/java/org/sopt/bofit/global/exception/custom_exception/UnAuthorizedException.java
  src/main/java/org/sopt/bofit/global/oauth/controller/OAuthController.java
  src/main/java/org/sopt/bofit/global/oauth/dto/KaKaoLoginResponse.java
  src/main/java/org/sopt/bofit/global/oauth/dto/KaKaoTokenResponse.java
  src/main/java/org/sopt/bofit/global/oauth/dto/KakaoUserResponse.java
  src/main/java/org/sopt/bofit/global/oauth/dto/TokenReissueResponse.java
  src/main/java/org/sopt/bofit/global/oauth/entity/RefreshToken.java
  src/main/java/org/sopt/bofit/global/oauth/jwt/CustomAccessDeniedHandler.java
  src/main/java/org/sopt/bofit/global/oauth/jwt/CustomAuthenticationEnrtyPoint.java
  src/main/java/org/sopt/bofit/global/oauth/jwt/JwtAuthenticationFilter.java
  src/main/java/org/sopt/bofit/global/oauth/jwt/JwtProvider.java
  src/main/java/org/sopt/bofit/global/oauth/jwt/JwtTokenAuthentication.java
  src/main/java/org/sopt/bofit/global/oauth/jwt/JwtUtil.java
  src/main/java/org/sopt/bofit/global/oauth/jwt/LoginArgumentResolver.java
  src/main/java/org/sopt/bofit/global/oauth/repository/RefreshTokenRepository.java
  src/main/java/org/sopt/bofit/global/oauth/service/OAuthService.java
  src/main/java/org/sopt/bofit/global/oauth/util/OAuthUtil.java
  src/main/java/org/sopt/bofit/global/oauth/util/UserAccountUtil.java
  src/main/java/org/sopt/bofit/global/response/BaseErrorResponse.java
  src/main/resources/application.yml
Labels: ✨ Feature, 🔥정연

#20 [Feat] 마이페이지 - 유저 정보 조회 API 구현
  src/main/java/org/sopt/bofit/domain/user/controller/UserController.java
  src/main/java/org/sopt/bofit/domain/user/dto/response/UserProfileResponse.java
  src/main/java/org/sopt/bofit/domain/user/entity/User.java
  src/main/java/org/sopt/bofit/domain/user/service/UserReadService.java
  src/main/java/org/sopt/bofit/domain/user/service/UserWriteService.java
  src/main/java/org/sopt/bofit/global/config/swagger/SwaggerResponseDescription.java
  src/main/java/org/sopt/bofit/global/exception/constant/UserErrorCode.java
  src/main/java/org/sopt/bofit/global/exception/custom_exception/NotFoundException.java
  src/main/java/org/sopt/bofit/global/oauth/controller/OAuthController.java
  src/main/java/org/sopt/bofit/global/response/BaseResponse.java
Labels: ✨ Feature, 🔥정연

#21 [Mod] 카카오 로그인 로직 수정
  src/main/java/org/sopt/bofit/domain/user/entity/User.java
  src/main/java/org/sopt/bofit/global/oauth/dto/KaKaoTokenResponse.java
  src/main/java/org/sopt/bofit/global/oauth/dto/KakaoUserResponse.java
  src/main/java/org/sopt/bofit/global/oauth/service/OAuthService.java
Labels: 🔥정연, 💻 Modification

#27 [Feat] 마이페이지 - 내가 쓴 글 조회 기능 구현
  build.gradle
  src/main/java/org/sopt/bofit/domain/post/entity/Post.java
  src/main/java/org/sopt/bofit/domain/post/repository/PostCustomRepository.java
  src/main/java/org/sopt/bofit/domain/post/repository/PostCustomRepositoryImpl.java
  src/main/java/org/sopt/bofit/domain/post/service/PostService.java
  src/main/java/org/sopt/bofit/domain/user/controller/UserController.java
  src/main/java/org/sopt/bofit/domain/user/dto/response/MyPostsResponse.java
  src/main/java/org/sopt/bofit/domain/user/dto/response/SliceResponse.java
  src/main/java/org/sopt/bofit/domain/user/service/UserReadService.java
  src/main/java/org/sopt/bofit/global/config/QueryDslConfig.java
  src/main/java/org/sopt/bofit/global/config/swagger/SwaggerResponseDescription.java
Labels: ✨ Feature, 🔥정연

#33 [Feat] 커뮤니티 - 게시물 수정 기능 구현
  src/main/java/org/sopt/bofit/domain/post/controller/PostController.java
  src/main/java/org/sopt/bofit/domain/post/entity/Post.java
  src/main/java/org/sopt/bofit/domain/post/service/PostService.java
  src/main/java/org/sopt/bofit/global/config/swagger/SwaggerResponseDescription.java
  src/main/java/org/sopt/bofit/global/exception/constant/PostErrorCode.java
  src/main/java/org/sopt/bofit/global/exception/custom_exception/ForbiddenException.java
Labels: ✨ Feature, 🔥정연

#44 [Feat] 보험 추천 리포트 상세 조회 구현
  build.gradle
  src/main/java/org/sopt/bofit/domain/insurance/controller/InsuranceController.java
  src/main/java/org/sopt/bofit/domain/insurancereport/constant/AdditionalInfo.java
  src/main/java/org/sopt/bofit/domain/insurancereport/dto/response/InsuranceReportDetailResponse.java
  src/main/java/org/sopt/bofit/domain/insurancereport/dto/response/IssueInsuranceReportResponse.java
  src/main/java/org/sopt/bofit/domain/insurancereport/dto/response/dailyHospitalization/DailyHospitalizationTotalSection.java
  src/main/java/org/sopt/bofit/domain/insurancereport/dto/response/death/DeathTotalSection.java
  src/main/java/org/sopt/bofit/domain/insurancereport/dto/response/disability/DisabilityTotalSection.java
  src/main/java/org/sopt/bofit/domain/insurancereport/dto/response/majordisease/CancerSection.java
  src/main/java/org/sopt/bofit/domain/insurancereport/dto/response/majordisease/CerebrovascularSection.java
  src/main/java/org/sopt/bofit/domain/insurancereport/dto/response/majordisease/HeartSection.java
  src/main/java/org/sopt/bofit/domain/insurancereport/dto/response/majordisease/MajorDiseaseTotalSection.java
  src/main/java/org/sopt/bofit/domain/insurancereport/dto/response/surgery/SurgeryTotalSection.java
  src/main/java/org/sopt/bofit/domain/insurancereport/errorcode/InsuranceReportErrorCode.java
  src/main/java/org/sopt/bofit/domain/insurancereport/repository/InsuranceReportRepository.java
  src/main/java/org/sopt/bofit/domain/insurancereport/service/InsuranceReportReader.java
  src/main/java/org/sopt/bofit/domain/insurancereport/service/InsuranceReportService.java
  src/main/java/org/sopt/bofit/domain/insurancereport/template/ReportPromptTemplate.java
  src/main/java/org/sopt/bofit/global/config/swagger/SwaggerResponseDescription.java
Labels: ✨ Feature, 🔥재헌

#48 [Feat] 커뮤니티 - 게시물 상세 조회 기능 구현
  src/main/java/org/sopt/bofit/domain/comment/repository/CommentRepository.java
  src/main/java/org/sopt/bofit/domain/post/controller/PostController.java
  src/main/java/org/sopt/bofit/domain/post/dto/response/PostDetailResponse.java
  src/main/java/org/sopt/bofit/domain/post/service/PostReader.java
  src/main/java/org/sopt/bofit/domain/post/service/PostService.java
  src/main/java/org/sopt/bofit/domain/post/service/PostWriter.java
  src/main/java/org/sopt/bofit/global/config/swagger/SwaggerResponseDescription.java
Labels: ✨ Feature, 🔥정연

#50 [Feat]보험 추천 리포트 조회 기능 분리
  src/main/java/org/sopt/bofit/domain/insurance/controller/InsuranceController.java
  src/main/java/org/sopt/bofit/domain/insurancereport/dto/response/InsuranceReportDetailResponse.java
  src/main/java/org/sopt/bofit/domain/insurancereport/dto/response/InsuranceReportResponse.java
  src/main/java/org/sopt/bofit/domain/insurancereport/dto/response/dailyHospitalization/DailyHospitalizationSection.java
  src/main/java/org/sopt/bofit/domain/insurancereport/dto/response/dailyHospitalization/DailyHospitalizationTotalSection.java
  src/main/java/org/sopt/bofit/domain/insurancereport/dto/response/death/DeathSection.java
  src/main/java/org/sopt/bofit/domain/insurancereport/dto/response/death/DeathTotalSection.java
  src/main/java/org/sopt/bofit/domain/insurancereport/dto/response/disability/DisabilitySection.java
  src/main/java/org/sopt/bofit/domain/insurancereport/dto/response/majordisease/CancerSection.java
  src/main/java/org/sopt/bofit/domain/insurancereport/dto/response/majordisease/CerebrovascularSection.java
  src/main/java/org/sopt/bofit/domain/insurancereport/dto/response/majordisease/HeartSection.java
  src/main/java/org/sopt/bofit/domain/insurancereport/dto/response/majordisease/MajorDiseaseSection.java
  src/main/java/org/sopt/bofit/domain/insurancereport/dto/response/majordisease/MajorDiseaseSubSection.java
  src/main/java/org/sopt/bofit/domain/insurancereport/dto/response/majordisease/MajorDiseaseTotalSection.java
  src/main/java/org/sopt/bofit/domain/insurancereport/dto/response/surgery/SurgerySection.java
  src/main/java/org/sopt/bofit/domain/insurancereport/dto/response/surgery/SurgeryTotalSection.java
  src/main/java/org/sopt/bofit/domain/insurancereport/dto/response/surgery/SurgeryTypeSection.java
  src/main/java/org/sopt/bofit/domain/insurancereport/entity/Disease.java
  src/main/java/org/sopt/bofit/domain/insurancereport/entity/scoringrule/ConditionCoverage.java
  src/main/java/org/sopt/bofit/domain/insurancereport/errorcode/InsuranceReportErrorCode.java
  src/main/java/org/sopt/bofit/domain/insurancereport/service/InsuranceReportService.java
  src/main/java/org/sopt/bofit/domain/user/controller/UserController.java
  src/main/java/org/sopt/bofit/global/config/swagger/SwaggerResponseDescription.java
Labels: ✨ Feature, 🔥재헌

#51 [Hotfix] 젠킨스 빌드 실패 해결
  src/main/java/org/sopt/bofit/domain/insurancereport/service/InsuranceReportWriter.java
Labels: 🐞 BugFix

#53 [Feat] 사용자의 가장 최근 InsuranceReport Summary 조회 API
  src/main/java/org/sopt/bofit/domain/insurancereport/dto/response/InsuranceReportResponse.java
  src/main/java/org/sopt/bofit/domain/insurancereport/dto/response/InsuranceReportSummaryResponse.java
  src/main/java/org/sopt/bofit/domain/insurancereport/dto/response/ShowCoverageStatus.java
  src/main/java/org/sopt/bofit/domain/insurancereport/entity/InsuranceReport.java
  src/main/java/org/sopt/bofit/domain/insurancereport/repository/InsuranceReportRepository.java
  src/main/java/org/sopt/bofit/domain/insurancereport/service/InsuranceReportReader.java
  src/main/java/org/sopt/bofit/domain/insurancereport/service/InsuranceReportService.java
  src/main/java/org/sopt/bofit/domain/user/controller/UserController.java
  src/main/java/org/sopt/bofit/global/config/swagger/SwaggerResponseDescription.java
Labels: ✨ Feature, 🔥재헌

#58 [Feat] 댓글 삭제 API 구현
  src/main/java/org/sopt/bofit/domain/comment/entity/Comment.java
  src/main/java/org/sopt/bofit/domain/comment/service/CommentReader.java
  src/main/java/org/sopt/bofit/domain/comment/service/CommentService.java
  src/main/java/org/sopt/bofit/domain/comment/service/CommentWriter.java
  src/main/java/org/sopt/bofit/domain/post/controller/PostController.java
  src/main/java/org/sopt/bofit/domain/post/entity/Post.java
  src/main/java/org/sopt/bofit/domain/user/entity/User.java
  src/main/java/org/sopt/bofit/global/config/swagger/SwaggerResponseDescription.java
  src/main/java/org/sopt/bofit/global/exception/constant/CommentErrorCode.java
  src/main/java/org/sopt/bofit/global/exception/custom_exception/ConflictException.java
Labels: ✨ Feature, 🔥재헌

#65 [Feat] 보장 상황 선택지 조회 API 구현
  src/main/java/org/sopt/bofit/domain/post/dto/response/PostDetailResponse.java
  src/main/java/org/sopt/bofit/domain/post/service/PostReader.java
  src/main/java/org/sopt/bofit/domain/user/controller/UserController.java
  src/main/java/org/sopt/bofit/domain/user/controller/UserInfoController.java
  src/main/java/org/sopt/bofit/domain/user/dto/response/CoveragePreferenceResponses.java
  src/main/java/org/sopt/bofit/domain/user/entity/constant/CoveragePreference.java
  src/main/java/org/sopt/bofit/domain/user/service/UserReader.java
  src/main/java/org/sopt/bofit/domain/user/service/UserService.java
Labels: ✨ Feature, 🔥재헌

#69 [Refactor] 세부 사항 리팩토링
  src/main/java/org/sopt/bofit/domain/comment/constant/CommentConstant.java
  src/main/java/org/sopt/bofit/domain/insurance/controller/InsuranceController.java
  src/main/java/org/sopt/bofit/domain/insurancereport/service/InsuranceReportWriter.java
  src/main/java/org/sopt/bofit/domain/post/constant/PostConstant.java
  src/main/java/org/sopt/bofit/domain/post/controller/PostController.java
  src/main/java/org/sopt/bofit/domain/user/controller/UserController.java
  src/main/java/org/sopt/bofit/domain/user/controller/UserInfoController.java
  src/main/java/org/sopt/bofit/global/constant/SwaggerConstant.java
  src/main/java/org/sopt/bofit/global/oauth/controller/OAuthController.java
  src/main/java/org/sopt/bofit/global/util/JsonUtil.java
Labels: 🔨 Refactor, 🔥재헌

#70 [Refactor] Security, JWT 관련 로직 리팩토링
  src/main/java/org/sopt/bofit/BofitApplication.java
  src/main/java/org/sopt/bofit/domain/post/service/PostWriter.java
  src/main/java/org/sopt/bofit/global/config/KakaoProperties.java
  src/main/java/org/sopt/bofit/global/config/SecurityConfig.java
  src/main/java/org/sopt/bofit/global/config/properties/JwtProperties.java
  src/main/java/org/sopt/bofit/global/config/properties/KakaoProperties.java
  src/main/java/org/sopt/bofit/global/oauth/constant/HttpHeaderConstants.java
  src/main/java/org/sopt/bofit/global/oauth/constant/JwtExceptionConstants.java
  src/main/java/org/sopt/bofit/global/oauth/constant/RequestAttributeConstants.java
  src/main/java/org/sopt/bofit/global/oauth/constant/SwaggerPathConstants.java
  src/main/java/org/sopt/bofit/global/oauth/controller/OAuthController.java
  src/main/java/org/sopt/bofit/global/oauth/jwt/CustomAccessDeniedHandler.java
  src/main/java/org/sopt/bofit/global/oauth/jwt/CustomAuthenticationEntryPoint.java
  src/main/java/org/sopt/bofit/global/oauth/jwt/JwtAuthenticationFilter.java
  src/main/java/org/sopt/bofit/global/oauth/jwt/JwtProvider.java
  src/main/java/org/sopt/bofit/global/oauth/jwt/JwtUtil.java
  src/main/java/org/sopt/bofit/global/oauth/service/OAuthService.java
Labels: 🔨 Refactor, 🔥정연

#74 [Refactor] 리포트 발급 수정
  src/main/java/org/sopt/bofit/domain/insurancereport/entity/Disease.java
  src/main/java/org/sopt/bofit/domain/insurancereport/entity/InsuranceReport.java
  src/main/java/org/sopt/bofit/domain/insurancereport/entity/constant/CoverageStatus.java
  src/main/java/org/sopt/bofit/domain/insurancereport/service/InsuranceReportWriter.java
  src/main/java/org/sopt/bofit/domain/insurancereport/template/ReportPromptTemplate.java
  src/main/java/org/sopt/bofit/domain/user/entity/UserInfo.java
  src/main/java/org/sopt/bofit/domain/user/repository/UserInfoRepository.java
  src/main/java/org/sopt/bofit/domain/user/service/UserInfoWriter.java
Labels: 🔨 Refactor, 🔥재헌

#82 [Feat] 토큰이 존재하지 않는 경우 예외처리 로직 추가
  src/main/java/org/sopt/bofit/global/exception/constant/GlobalErrorCode.java
  src/main/java/org/sopt/bofit/global/oauth/constant/JwtExceptionConstants.java
  src/main/java/org/sopt/bofit/global/oauth/jwt/CustomAuthenticationEntryPoint.java
  src/main/java/org/sopt/bofit/global/oauth/jwt/JwtAuthenticationFilter.java
Labels: ✨ Feature, 🔥재헌

#84 [Chore] 유저 정보 조회 DTO에 유저 이름 추가
  src/main/java/org/sopt/bofit/domain/user/dto/response/UserProfileResponse.java
  src/main/java/org/sopt/bofit/domain/user/service/UserReader.java
Labels: 🔥정연, 🎨 Chore

#86 [Hotfix] 필터의 shouldNotFilter 경로 수정
  src/main/java/org/sopt/bofit/global/oauth/constant/PathConstant.java
  src/main/java/org/sopt/bofit/global/oauth/jwt/JwtAuthenticationFilter.java
Labels: 🐞 BugFix, 🔥재헌

#88 [Chore] #87 shouldNotFilter 경로 오타 수정
  src/main/java/org/sopt/bofit/global/oauth/constant/PathConstant.java
Labels: 🔥정연, 🎨 Chore

#93 [Fix] 토큰 재발급 필터 부분 수정
  src/main/java/org/sopt/bofit/domain/comment/repository/CommentCustomRepositoryImpl.java
  src/main/java/org/sopt/bofit/global/config/SecurityConfig.java
  src/main/java/org/sopt/bofit/global/oauth/jwt/JwtAuthenticationFilter.java
Labels: 🐞 BugFix, 🔥재헌

#96 [Refactor] 외부 API 요청 RestClient 방식으로 변경
  src/main/java/org/sopt/bofit/BofitApplication.java
  src/main/java/org/sopt/bofit/global/config/properties/OpenAiProperties.java
  src/main/java/org/sopt/bofit/global/external/openai/client/OpenAiClient.java
  src/main/java/org/sopt/bofit/global/oauth/controller/OAuthController.java
  src/main/java/org/sopt/bofit/global/oauth/jwt/JwtAuthenticationFilter.java
  src/main/java/org/sopt/bofit/global/oauth/service/OAuthService.java
Labels: 🔨 Refactor, 🔥정연

#102 [Fix] 글 삭제 시 달린 댓글도 함께 삭제하도록 수정
  src/main/java/org/sopt/bofit/domain/post/service/PostWriter.java
Labels: 🐞 BugFix, 🔥정연

#104 [Mod] 프롬프트 및 상수 텍스트 수정
  src/main/java/org/sopt/bofit/domain/insurancereport/constant/AdditionalInfo.java
  src/main/java/org/sopt/bofit/domain/insurancereport/entity/Disease.java
  src/main/java/org/sopt/bofit/domain/insurancereport/entity/scoringrule/ConditionCoverage.java
  src/main/java/org/sopt/bofit/domain/insurancereport/template/ReportPromptTemplate.java
  src/main/java/org/sopt/bofit/domain/user/entity/constant/CoveragePreference.java
Labels: 🔥재헌, 💻 Modification

#108 [Chore] 리포트 항목 공백 수정
  src/main/java/org/sopt/bofit/domain/insurancereport/constant/AdditionalInfo.java
  src/main/java/org/sopt/bofit/domain/insurancereport/entity/Disease.java
Labels: 🔥재헌, 🎨 Chore
