Repository team-bofit/bofit-server, pull requests merged in 2025-09, with the labels that each got.

#130 [Feat] S3 세팅 및 presigned URL 발급 기능 구현
  build.gradle
  src/main/java/org/sopt/bofit/BofitApplication.java
  src/main/java/org/sopt/bofit/global/config/S3Config.java
  src/main/java/org/sopt/bofit/global/config/properties/S3Properties.java
  src/main/java/org/sopt/bofit/global/config/swagger/SwaggerResponseDescription.java
  src/main/java/org/sopt/bofit/global/exception/constant/S3ErrorCode.java
  src/main/java/org/sopt/bofit/global/s3/constant/ContentTypeConstants.java
  src/main/java/org/sopt/bofit/global/s3/controller/FileController.java
  src/main/java/org/sopt/bofit/global/s3/dto/request/PresignedUrlRequest.java
  src/main/java/org/sopt/bofit/global/s3/dto/response/PresignedUrlResponse.java
  src/main/java/org/sopt/bofit/global/s3/service/FileService.java
  src/main/java/org/sopt/bofit/global/s3/util/ContentTypeUtil.java
  src/main/java/org/sopt/bofit/global/s3/util/KeyGenerator.java
  src/main/java/org/sopt/bofit/global/s3/util/PresignedUrlCreator.java
  src/main/resources/application.yml
Labels: ✨ Feature, 🔥정연

#133 [Fix] #132 test용 yml 파일에도 S3 관련 변수 추가
  src/test/resources/application-test.yml
Labels: 🐞 BugFix, 🔥정연

#150 [Feat] Full Text Search 이용한 게시물 검색 기능 구현
  src/main/java/org/sopt/bofit/domain/comment/service/CommentService.java
  src/main/java/org/sopt/bofit/domain/post/controller/PostController.java
  src/main/java/org/sopt/bofit/domain/post/dto/response/PostDetailResponse.java
  src/main/java/org/sopt/bofit/domain/post/dto/response/PostSummaryResponse.java
  src/main/java/org/sopt/bofit/domain/post/entity/Post.java
  src/main/java/org/sopt/bofit/domain/post/repository/PostCustomRepository.java
  src/main/java/org/sopt/bofit/domain/post/repository/PostCustomRepositoryImpl.java
  src/main/java/org/sopt/bofit/domain/post/repository/PostRepository.java
  src/main/java/org/sopt/bofit/domain/post/service/PostReader.java
  src/main/java/org/sopt/bofit/domain/post/service/PostService.java
  src/main/java/org/sopt/bofit/domain/post/service/PostWriter.java
  src/main/java/org/sopt/bofit/domain/user/dto/response/MyPostSummaryResponse.java
  src/main/java/org/sopt/bofit/domain/user/service/UserWriter.java
  src/main/java/org/sopt/bofit/global/config/FullTextFunctions.java
  src/main/java/org/sopt/bofit/global/config/swagger/SwaggerResponseDescription.java
  src/main/resources/META-INF/services/org.hibernate.boot.model.FunctionContributor
Labels: ✨ Feature, 🔥정연

#153 [Feat] 대댓글 수정 API 구현
  src/main/java/org/sopt/bofit/domain/comment/entity/Comment.java
  src/main/java/org/sopt/bofit/domain/comment/entity/CommentImage.java
  src/main/java/org/sopt/bofit/domain/comment/repository/CommentImageRepository.java
  src/main/java/org/sopt/bofit/domain/comment/service/CommentImageReader.java
  src/main/java/org/sopt/bofit/domain/comment/service/CommentImageWriter.java
  src/main/java/org/sopt/bofit/domain/comment/service/CommentService.java
  src/main/java/org/sopt/bofit/domain/commentreply/dto/request/CommentReplyUpdateRequest.java
  src/main/java/org/sopt/bofit/domain/commentreply/entity/CommentReply.java
  src/main/java/org/sopt/bofit/domain/commentreply/entity/CommentReplyImage.java
  src/main/java/org/sopt/bofit/domain/commentreply/entity/CommentReplyImageStatus.java
  src/main/java/org/sopt/bofit/domain/commentreply/entity/CommentReplyStatus.java
  src/main/java/org/sopt/bofit/domain/commentreply/repository/CommentReplyImageRepository.java
  src/main/java/org/sopt/bofit/domain/commentreply/repository/CommentReplyRepository.java
  src/main/java/org/sopt/bofit/domain/commentreply/service/CommentReplyImageReader.java
  src/main/java/org/sopt/bofit/domain/commentreply/service/CommentReplyImageWriter.java
  src/main/java/org/sopt/bofit/domain/commentreply/service/CommentReplyReader.java
  src/main/java/org/sopt/bofit/domain/commentreply/service/CommentReplyService.java
  src/main/java/org/sopt/bofit/domain/commentreply/service/dto/request/CommentReplyUpdateCommand.java
  src/main/java/org/sopt/bofit/domain/post/controller/PostController.java
  src/main/java/org/sopt/bofit/global/config/swagger/SwaggerResponseDescription.java
  src/main/java/org/sopt/bofit/global/exception/constant/CommentReplyErrorCode.java
Labels: ✨ Feature, 🔥재헌

#155 [Refactor] 이미지 수정 로직 리팩토링
  src/main/java/org/sopt/bofit/domain/comment/entity/CommentImage.java
  src/main/java/org/sopt/bofit/domain/comment/service/CommentImageWriter.java
  src/main/java/org/sopt/bofit/domain/comment/service/CommentService.java
  src/main/java/org/sopt/bofit/domain/comment/service/dto/request/CommentCreateCommand.java
  src/main/java/org/sopt/bofit/domain/commentreply/entity/CommentReplyImage.java
  src/main/java/org/sopt/bofit/domain/commentreply/service/CommentReplyImageWriter.java
  src/main/java/org/sopt/bofit/domain/commentreply/service/CommentReplyService.java
  src/main/java/org/sopt/bofit/domain/post/controller/PostController.java
  src/main/java/org/sopt/bofit/domain/post/dto/request/PostCreateRequest.java
  src/main/java/org/sopt/bofit/domain/post/dto/request/PostUpdateRequest.java
  src/main/java/org/sopt/bofit/domain/post/entity/PostImage.java
  src/main/java/org/sopt/bofit/domain/post/entity/constant/PostImageStatus.java
  src/main/java/org/sopt/bofit/domain/post/repository/PostImageRepository.java
  src/main/java/org/sopt/bofit/domain/post/service/PostImageReader.java
  src/main/java/org/sopt/bofit/domain/post/service/PostImageWriter.java
  src/main/java/org/sopt/bofit/domain/post/service/PostService.java
  src/main/java/org/sopt/bofit/domain/post/service/PostWriter.java
  src/main/java/org/sopt/bofit/domain/post/service/dto/request/PostCreateCommand.java
  src/main/java/org/sopt/bofit/domain/post/service/dto/request/PostUpdateCommand.java
  src/main/java/org/sopt/bofit/global/exception/constant/PostErrorCode.java
  src/main/java/org/sopt/bofit/global/file/util/ImageValidator.java
Labels: 🔨 Refactor, 🔥정연

#159 [Refactor] 보험 추천 리포트 저장 로직 리팩토링
  src/main/java/org/sopt/bofit/domain/insurancereport/service/InsuranceReportService.java
  src/main/java/org/sopt/bofit/domain/insurancereport/service/InsuranceReportWriter.java
  src/test/java/org/sopt/bofit/domain/insurancereport/service/InsuranceReportWriterTest.java
Labels: 🔨 Refactor, 🔥재헌

#161 [Feat] 대댓글 목록 조회 API 구현
  src/main/java/org/sopt/bofit/domain/commentreply/constant/CommentReplyConstant.java
  src/main/java/org/sopt/bofit/domain/commentreply/dto/response/CommentReplyWithImagesResponse.java
  src/main/java/org/sopt/bofit/domain/commentreply/entity/CommentReplyImage.java
  src/main/java/org/sopt/bofit/domain/commentreply/repository/CommentReplyCustomRepository.java
  src/main/java/org/sopt/bofit/domain/commentreply/repository/CommentReplyCustomRepositoryImpl.java
  src/main/java/org/sopt/bofit/domain/commentreply/repository/CommentReplyImageRepository.java
  src/main/java/org/sopt/bofit/domain/commentreply/repository/CommentReplyJpaRepository.java
  src/main/java/org/sopt/bofit/domain/commentreply/repository/CommentReplyRepository.java
  src/main/java/org/sopt/bofit/domain/commentreply/service/CommentReplyImageReader.java
  src/main/java/org/sopt/bofit/domain/commentreply/service/CommentReplyReader.java
  src/main/java/org/sopt/bofit/domain/commentreply/service/CommentReplyService.java
  src/main/java/org/sopt/bofit/domain/commentreply/service/dto/response/CommentReplyImageResponse.java
  src/main/java/org/sopt/bofit/domain/commentreply/service/dto/response/CommentReplyResponse.java
  src/main/java/org/sopt/bofit/domain/post/controller/PostController.java
Labels: ✨ Feature, 🔥재헌

#167 [Feat] 검색어가 1글자인 경우 like 연산 수행하도록 구현
  src/main/java/org/sopt/bofit/domain/post/repository/PostCustomRepositoryImpl.java
  src/main/java/org/sopt/bofit/domain/post/repository/PostRepository.java
Labels: ✨ Feature, 🔥정연
