Repository team-bofit/bofit-server, pull requests merged in 2025-10, with the labels that each got.

#200 [Fix] 게시글 상세 조회 시 좋아요 여부 반영 수정
  src/main/java/org/sopt/bofit/domain/post/dto/response/PostDetailResponse.java
  src/main/java/org/sopt/bofit/domain/post/service/PostReader.java
  src/main/java/org/sopt/bofit/domain/post/service/PostService.java
Labels: 🐞 BugFix, 🔥재헌

#202 [Chore] PATCH 요청도 CORS 허용하도록 수정
  src/main/java/org/sopt/bofit/global/config/WebConfig.java
Labels: 🔥정연, 🎨 Chore

#203 [Fix] 게시물 검색 시 중복 페이지 반환되는 문제 수정
  src/main/java/org/sopt/bofit/domain/post/controller/PostController.java
  src/main/java/org/sopt/bofit/domain/post/dto/response/PostSearchResponse.java
  src/main/java/org/sopt/bofit/domain/post/repository/PostCustomRepository.java
  src/main/java/org/sopt/bofit/domain/post/repository/PostCustomRepositoryImpl.java
  src/main/java/org/sopt/bofit/domain/post/service/PostReader.java
  src/main/java/org/sopt/bofit/domain/post/service/PostService.java
Labels: 🐞 BugFix, 🔥정연
